Dw 14 styles header
team-desarrollo-web/stage-1-html-css pull request #21
Opened 2023-10-26 14:15 UTC by LautaroTinelli

# [DW-14: Add styles to Header](https://trello.com/c/q8htUtXn/117-dw-14-add-styles-to-header)

## Type of change

> Exchange rate entered. The possible values ​​for this section are:
>
> - Feature (new feature of the server/application)

## Description

> - Add icons and center phone number and times.
> - Add styles to navbar.

## Attachments

![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/144698872/84983819-fa4f-4470-9224-31eae4ae4ad9)

![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/144698872/920f75b2-2a5a-49b2-b658-7d5a136ac3ff)

2023-10-28 13:24 UTC, maxidelfino commented on index.html
>        <div>
Remove this <div> it is unnecessary

2023-10-28 13:43 UTC, maxidelfino requested changes

2023-10-28 13:43 UTC, maxidelfino commented on src/styles/index.css
Check the typography of the letters. Must match the figma.
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/89036646/18994947-bca0-4a01-a892-e19db0663cc4)
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/89036646/f5527053-3570-4d9d-b72d-e028bcb91670)

2023-10-28 13:43 UTC, maxidelfino commented on src/pages/about-us/index.html
> +    <div>
Remove this <div> it is unnecessary

2023-10-28 13:43 UTC, maxidelfino commented on src/styles/index.css
On mobile phones and tablets, the background color of the links must be respected!
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/89036646/5b5fb298-36f4-4ae2-b93d-a415c77466d9)
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/89036646/027cb9a3-c593-4ef0-9540-7bcaa49fcc94)

2023-10-28 13:43 UTC, maxidelfino commented on src/styles/index.css
Remove border to toggler button

2023-10-28 13:43 UTC, maxidelfino commented on src/styles/index.css
Delete background-color of icons
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/89036646/afc3edad-2110-4bcb-836a-3dadf7012a78)
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/89036646/979248bd-ba2a-425b-afff-36e9c6057b56)

2023-10-28 13:43 UTC, maxidelfino commented on src/styles/index.css
> +  border-bottom: 2px solid #d9ba85;
Add   `transition: all 0.5s;`  to maintain consistency

2023-11-01 22:48 UTC, LautaroTinelli commented on src/styles/index.css
Done

2023-11-01 22:49 UTC, LautaroTinelli commented on src/styles/index.css
Done

2023-11-11 17:40 UTC, maxidelfino approved these changes

2023-11-13 10:13 UTC, TomiJortiz approved these changes

2023-11-15 23:13 UTC, merged