DW-19: Add styles to Menu section
team-desarrollo-web/stage-1-html-css pull request #23
Opened 2023-12-05 01:00 UTC by TomiJortiz

# [DW-19: Add styles to Menu section](https://trello.com/c/uI9sLRM1/122-dw-19-add-styles-to-menu-section)

> Ticket code, title of the ticket and as a hyperlink, the corresponding TRELLO link

## Type of change

> Exchange rate entered. The possible values ​​for this section are:
>
> - Feature (new feature of the server/application)

## Description

> - Add styles to Menu section

## Attachments
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/141139876/6c1f84fa-b24d-4674-a335-cca87d2a5fed)

![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/141139876/588ae567-fd4f-4994-8731-c26139b4cdb9)

![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/141139876/45299025-ed8d-4a19-9d55-fa9ee4cd4a54)

2023-12-05 22:39 UTC, maxidelfino commented on .vscode/settings.json
> +    "liveServer.settings.port": 5501
Why this code line?

2023-12-05 22:52 UTC, maxidelfino commented on src/pages/menu-specials/index.css
> +/* stylelint-disable no-descending-specificity */
Delete this comment

2023-12-05 22:57 UTC, maxidelfino commented on src/pages/menu-specials/index.css
> +  font-family: 'Poppins', sans-serif;
Remove this font-family

2023-12-05 23:18 UTC, maxidelfino requested changes

2023-12-05 23:18 UTC, maxidelfino commented on src/pages/menu-specials/index.css
> +  /* width: 1000px; */
Delete this comment

2023-12-05 23:18 UTC, maxidelfino commented on src/pages/menu-specials/index.css
> +.menu-container {
This code is repeated in several parts:

```
{
  display: flex;
  flex-direction: column;
  align-items: center;
}
```

We should avoid repeating code. Maybe we could do the following:

```
.menu-container,
.menu-container__title,
.father-container__item {
  display: flex;
  flex-direction: column;
  align-items: center;
}
```

```
.menu-container {
  padding: 0;
  background-color: #1a1a1a;
}

.menu-container__title {
  justify-content: center;
  color: #ffffff;
}

.father-container__item {
  width: 20%;
  min-width: 380px;
  margin-top: 30px;
  margin-bottom: 50px;
}
```

2023-12-05 23:18 UTC, maxidelfino commented on src/pages/menu-specials/index.html
> +    <!-- bootstrap trabaja asi: .container - .container-fluid > .row > col-*-* -->
Delete this comment

2023-12-05 23:18 UTC, maxidelfino commented on src/pages/menu-specials/index.html
> +me
Remove this

2023-12-05 23:18 UTC, maxidelfino commented on src/pages/menu-specials/index.css
> +  text-decoration: none !important;
Delete this `important`

2023-12-07 12:36 UTC, LautaroTinelli approved these changes

2023-12-07 23:57 UTC, LautaroTinelli approved these changes

2023-12-07 23:57 UTC, maxidelfino approved these changes
🚀

2023-12-07 23:57 UTC, merged