DW-24: Add styles to WhatsApp Icon
team-desarrollo-web/stage-1-html-css pull request #24
Opened 2023-12-13 22:07 UTC by LautaroTinelli

# [DW-24: Add styles to WhatsApp Icon](https://trello.com/c/Hp5M0P7J/127-dw-24-add-styles-to-whatsapp-icon)

## Type of change

> - Feature (new feature of the server/application)

## Description

> - Icon relocation and its size.
> - Add an animation.
> - Set a background color.

## Attachments

![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/144698872/7f774efc-707e-4834-afdb-9f9575fc77ed)
![image](https://github.com/team-desarrollo-web/stage-1-html-css/assets/144698872/afc25826-3d09-421f-8558-572a48ad0c58)

2023-12-13 23:27 UTC, maxidelfino approved these changes
🚀

2023-12-14 22:00 UTC, Yamirod submitted a review, later dismissed

2023-12-14 22:27 UTC, maxidelfino requested changes

2023-12-14 22:27 UTC, maxidelfino commented on src/styles/whatsapp-icon.css
> +main section h2 {
Remove this style because it affects all h2 elements that are within a section tag and the main tag

2023-12-14 22:43 UTC, maxidelfino approved these changes

2023-12-14 22:54 UTC, Yamirod approved these changes

2023-12-14 22:54 UTC, merged

2023-12-14 22:57 UTC, TomiJortiz approved these changes